apiVersion: v1
kind: pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
  image: nginx
  env: 
    - name: "course"
      valueFrom:
            configMapKeyRef:
              name: swethakanala           # The ConfigMap this value comes from.
              key: "course"
    - name: "trainer"
      valueFrom:
            configMapKeyRef:
               name: swethakanala
               key: "sivakumar"

