apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: swethakanala
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: swethakanala
          key: course
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: swethakanala
          key: trainer

