apiversion: v1
kind: pod
metadata:
    name: pod-config
spec:
  containers:
  - name: nginx
  image: nginx
  env: 
    configMapKeyRef:
       name: daws78s

#env:
# - name: course
#   valuefrom:
#   configMapkeyRef:
#       name: daws78s
#       key: course
# - name: trainer
#   valuefrom:
#      configMapKeyRef:
#         name: daws78s
#         key: trainer 

       