kind: Deployment
apiVersion: app/v1
metadata:
   name: nginx
   # these labels are deployment related labels.
   labels: 
     app: nginx
     purpose: deployment
     tier: web
   spec:
     replicas: 20
     selector:
        matchLabels:
          app: nginx
          tier: web
          project: test-project
    # pod defination
template:
  metadata: 
    Labels:
      app: nginx
      tier: web
      project: test-project
      extra-key: extra-value
  spec:
   containers:
   - name: nginx
     image: nginx