kind: Deployment
apiVersion: app/v1
metadata:
   name: nginx
   # these labels are deployment related labels.
   labels: 
     app: nginx
     purpose: deployment
     tier: web
spec:
     replicas: 5
     selector:
        matchLabels:
          app: nginx
          tier: web
          project: test-project
    # pod defination
template:
  metadata: 
    Labels:
      app: nginx
      tier: web
      project: test-project
      extra-key: extra-value
  spec:
   containers:
   - name: nginx
     image: nginx
  
---

apiversion: v1
kind: service
metadata: 
 name: nginx
spec: 
 selector:
      app: nginx
      tier: web
      project: test-project
      extra-key: extra-value
ports:
    - protocol: TCP
      port: 80  #service-port
      targetport: 80 #target-port